AVANCE 2

Conectarse a la API de Yelp para obtener información de negocios locales de una ciudad segun el pais seleccionado.
Extraer datos como nombre del negocio, categoria, calificación, número de reseñas, calificaciones, etc.

Integrar esta información al análisis que se está realizando para una ciudad/pais en especifico

Documentar los resultados en Avance_2_API_Yelp.ipynb

1. CONEXION Y EXTRACCION DE INFORMACIÓN A PARTIR DE LA API

In [1]:
#Importamos las librerias necesarias
import requests
import pandas as pd
import load_dotenv
import numpy as np

In [2]:
#Nos conectamos a la API de Yelp y validamos la credencial

url = "https://api.yelp.com/v3/businesses/search"
YELP_API_KEY= 'FHVvXoNmTXIl9DuxYis7AV5uLPujm9MLwrhgs5NgvCfaOxd3V6mxt6dQU8eEqYJiGxe816XATx7ufWjbMWqbV-2Uku1jxBJv8BGRC74NroLPl27PDQqs0tDixit-YHYx'

In [3]:
#Definimos los parametros de solicitud y armamos una función que integre 200 filas a partir de solicitudes de 50 datos

headers = {'Authorization': f'Bearer {YELP_API_KEY}'}
ciudad = 'Boston'

total_rows = 200
limit = 50
resultados = []

for offset in range(0, total_rows, limit):
    params = {
        "term": "restaurant",
        "location": ciudad,
        "limit": limit,
        "offset": offset
    }
    
    response = requests.get("https://api.yelp.com/v3/businesses/search", 
                            params=params, headers=headers)
    data = response.json()
    
    # Agregamos lo que vino a nuestra lista
    resultados.extend(data.get("businesses", []))

# Convertimos a DataFrame
df_rest = pd.DataFrame(resultados)

In [4]:
df_rest

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance
0,kP1b-7BO_VhWk_0tvuA_tw,carmelinas-boston-2,Carmelina's,https://s3-media0.fl.yelpcdn.com/bphoto/rxZBwI...,False,https://www.yelp.com/biz/carmelinas-boston-2?a...,4126,"[{'alias': 'italian', 'title': 'Italian'}]",4.5,"{'latitude': 42.36388, 'longitude': -71.05415}","[restaurant_reservation, delivery]",$$$,"{'address1': '307 Hanover St', 'address2': '',...",+16177420020,(617) 742-0020,2272.117192
1,sA2gVTJOBH7Qk32p48ENdQ,saltie-girl-boston,Saltie Girl,https://s3-media0.fl.yelpcdn.com/bphoto/C8SL95...,False,https://www.yelp.com/biz/saltie-girl-boston?ad...,2500,"[{'alias': 'seafood', 'title': 'Seafood'}, {'a...",4.2,"{'latitude': 42.35116, 'longitude': -71.07758}","[pickup, delivery]",$$$,"{'address1': '279 Dartmouth St', 'address2': '...",+16172670691,(617) 267-0691,638.213544
2,xh-i6tYmojnnUHrnkFnWdA,willow-and-ivy-boston,Willow & Ivy,https://s3-media0.fl.yelpcdn.com/bphoto/eIGgkA...,False,https://www.yelp.com/biz/willow-and-ivy-boston...,31,"[{'alias': 'newamerican', 'title': 'New Americ...",4.7,"{'latitude': 42.349126, 'longitude': -71.079754}",[],NaN,"{'address1': '65 Exeter St', 'address2': None,...",+16179334800,(617) 933-4800,713.579578
3,t_FFcwUutj9mIYKGw_gHsQ,the-salty-pig-boston,The Salty Pig,https://s3-media0.fl.yelpcdn.com/bphoto/y-_CvQ...,False,https://www.yelp.com/biz/the-salty-pig-boston?...,2040,"[{'alias': 'newamerican', 'title': 'New Americ...",4.2,"{'latitude': 42.3469, 'longitude': -71.076121}",[delivery],$$,"{'address1': '130 Dartmouth St', 'address2': '...",+16175366200,(617) 536-6200,414.307221
4,JYoptTywH42iRjMaE925BA,isabella-ristorante-boston,Isabella Ristorante,https://s3-media0.fl.yelpcdn.com/bphoto/6IPkeX...,False,https://www.yelp.com/biz/isabella-ristorante-b...,571,"[{'alias': 'italian', 'title': 'Italian'}]",4.5,"{'latitude': 42.36403, 'longitude': -71.05362}",[],$$,"{'address1': '2 Prince St', 'address2': '', 'a...",+16172277300,(617) 227-7300,2311.555147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,rdpY_LeMnDnfeK47eDnDOw,lincoln-tavern-and-restaurant-boston,Lincoln Tavern & Restaurant,https://s3-media0.fl.yelpcdn.com/bphoto/3vHjkC...,False,https://www.yelp.com/biz/lincoln-tavern-and-re...,1190,"[{'alias': 'newamerican', 'title': 'New Americ...",3.9,"{'latitude': 42.336323, 'longitude': -71.0476}",[delivery],$$,"{'address1': '425 W Broadway', 'address2': '',...",+16177658636,(617) 765-8636,2327.340791
196,n7kjRf3hMYDhCqxG6iC4Cg,orinoco-cambridge,Orinoco,https://s3-media0.fl.yelpcdn.com/bphoto/tdvp72...,False,https://www.yelp.com/biz/orinoco-cambridge?adj...,394,"[{'alias': 'venezuelan', 'title': 'Venezuelan'...",4.0,"{'latitude': 42.3718793590212, 'longitude': -7...","[delivery, pickup]",$$,"{'address1': '56 John F Kennedy St', 'address2...",+16173546900,(617) 354-6900,4855.125485
197,Jmyya_ylt3Bks4NTcyWgEg,zuma-boston-2,Zuma,https://s3-media0.fl.yelpcdn.com/bphoto/gv1Lr1...,False,https://www.yelp.com/biz/zuma-boston-2?adjust_...,390,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",4.0,"{'latitude': 42.34591732031346, 'longitude': -...","[delivery, pickup]",$$$$,"{'address1': '1 Dalton St', 'address2': 'Fl 2'...",+18574492500,(857) 449-2500,1081.960420
198,gM4sz4LasKhCtkgIFI56UA,dovetail-restaurant-and-shop-boston,Dovetail Restaurant & Shop,https://s3-media0.fl.yelpcdn.com/bphoto/YMlgDH...,False,https://www.yelp.com/biz/dovetail-restaurant-a...,69,"[{'alias': 'wine_bars', 'title': 'Wine Bars'},...",4.4,"{'latitude': 42.37523157393522, 'longitude': -...",[],NaN,"{'address1': '1 6th St', 'address2': '', 'addr...",+16173375070,(617) 337-5070,3341.046362
199,Z6Io2AbJrof7TPVliMZkAg,fuji-at-ink-block-boston,Fuji at Ink Block,https://s3-media0.fl.yelpcdn.com/bphoto/WrMocX...,False,https://www.yelp.com/biz/fuji-at-ink-block-bos...,765,"[{'alias': 'japanese', 'title': 'Japanese'}, {...",4.5,"{'latitude': 42.345077, 'longitude': -71.063505}","[delivery, pickup]",$$$,"{'address1': '352 Harrison Ave', 'address2': '...",+16179363282,(617) 936-3282,706.357329

In [5]:
df_rest.dtypes

id                object
alias             object
name              object
image_url         object
is_closed           bool
url               object
review_count       int64
categories        object
rating           float64
coordinates       object
transactions      object
price             object
location          object
phone             object
display_phone     object
distance         float64
dtype: object

2. ANALISIS DE VALIDACIÓN DE LA INFORMACIÓN POR COLUMNA

In [6]:
#Observamos insistencias en los datos, empezando por los nulos. Observamos 57 valores nulos en la columna price que mas adelante rellenaremos

nulos = df_rest.isnull().sum()
print(nulos)

id                0
alias             0
name              0
image_url         0
is_closed         0
url               0
review_count      0
categories        0
rating            0
coordinates       0
transactions      0
price            57
location          0
phone             0
display_phone     0
distance          0
dtype: int64

In [7]:
#Eliminamos columnas innecesarias
df_rest = df_rest.drop(columns=['image_url', "is_closed" ])

In [8]:
#verificamos duplicidad en la información
print(df_rest['id'].duplicated().sum())

0

In [9]:
df_rest['price'].unique()

array(['$$$', nan, '$$', '$$$$', '$'], dtype=object)

In [10]:
#Para rellenar los nulos, primero observamos que el price es un texto, deberiamos asignarle un valor numerico
df_rest['price'].dtype

dtype('O')

Relleno de nulos en la columna precio

In [11]:
#El proceso de asignación de valor consiste en crear una columna nueva asignando a cada $ un valor numerico

df_rest['price_num'] = df_rest['price'].map({
    '$': 1,
    '$$': 2,
    '$$$': 3,
    '$$$$': 4
}).astype('Int64')

df_rest['price_num']

0         3
1         3
2      <NA>
3         2
4         2
       ...
195       2
196       2
197       4
198    <NA>
199       3
Name: price_num, Length: 200, dtype: Int64

In [12]:
#Para aquellos precios que quedaron sin asignarles un valor, buscaremos asignarle uno a partir de información de otras columnas. En este caso, 
# tomamos como variable de referencia "categories" para internar estimar el valor del precio de los restaurantes
#EL problema es que las categorias se encuentran en un formato de lista de diccionarios, con lo cual debemos hacer un proceso de extraccion de las mismas, 
# Creamos una nueva columna, llamada 'category_title' donde le asginamos a cada una el valor de acuerdo a su restaurante
df_exploded = df_rest.explode('categories').reset_index(drop=True)
df_exploded['category_title'] = df_exploded['categories'].apply(lambda x: x.get('title') if isinstance(x, dict) else None)
df_exploded.head()

,id,alias,name,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance,price_num,category_title
0,kP1b-7BO_VhWk_0tvuA_tw,carmelinas-boston-2,Carmelina's,https://www.yelp.com/biz/carmelinas-boston-2?a...,4126,"{'alias': 'italian', 'title': 'Italian'}",4.5,"{'latitude': 42.36388, 'longitude': -71.05415}","[restaurant_reservation, delivery]",$$$,"{'address1': '307 Hanover St', 'address2': '',...",+16177420020,(617) 742-0020,2272.117192,3,Italian
1,sA2gVTJOBH7Qk32p48ENdQ,saltie-girl-boston,Saltie Girl,https://www.yelp.com/biz/saltie-girl-boston?ad...,2500,"{'alias': 'seafood', 'title': 'Seafood'}",4.2,"{'latitude': 42.35116, 'longitude': -71.07758}","[pickup, delivery]",$$$,"{'address1': '279 Dartmouth St', 'address2': '...",+16172670691,(617) 267-0691,638.213544,3,Seafood
2,sA2gVTJOBH7Qk32p48ENdQ,saltie-girl-boston,Saltie Girl,https://www.yelp.com/biz/saltie-girl-boston?ad...,2500,"{'alias': 'cocktailbars', 'title': 'Cocktail B...",4.2,"{'latitude': 42.35116, 'longitude': -71.07758}","[pickup, delivery]",$$$,"{'address1': '279 Dartmouth St', 'address2': '...",+16172670691,(617) 267-0691,638.213544,3,Cocktail Bars
3,xh-i6tYmojnnUHrnkFnWdA,willow-and-ivy-boston,Willow & Ivy,https://www.yelp.com/biz/willow-and-ivy-boston...,31,"{'alias': 'newamerican', 'title': 'New American'}",4.7,"{'latitude': 42.349126, 'longitude': -71.079754}",[],NaN,"{'address1': '65 Exeter St', 'address2': None,...",+16179334800,(617) 933-4800,713.579578,<NA>,New American
4,xh-i6tYmojnnUHrnkFnWdA,willow-and-ivy-boston,Willow & Ivy,https://www.yelp.com/biz/willow-and-ivy-boston...,31,"{'alias': 'desserts', 'title': 'Desserts'}",4.7,"{'latitude': 42.349126, 'longitude': -71.079754}",[],NaN,"{'address1': '65 Exeter St', 'address2': None,...",+16179334800,(617) 933-4800,713.579578,<NA>,Desserts

In [13]:
#Posteriormente generamos una lista de precios para cada categoria en función del promedio de las que aparecen del total de restaurantes
df_category_prices = df_exploded.groupby('category_title', as_index=False)['price_num'].mean()
df_category_prices['price_num'] = df_category_prices['price_num'].astype('Int64')
df_category_prices

           category_title  price_num
0                  Afghan          3
1                American          2
2                  Arabic       <NA>
3                Armenian          2
4            Asian Fusion          2
..                    ...        ...
84                Turkish          2
85             Venezuelan          2
86  Venues & Event Spaces          2
87             Vietnamese          2
88              Wine Bars          2

[89 rows x 2 columns]

In [14]:
#Finalmente, asginamos estos resultados en función de las categorias que tenga cada restaurante cuyo precio sea NAN

df_exp = df_rest.explode('categories').reset_index(drop=True)

# Extraer el título de cada categoría
df_exp['category_title'] = df_exp['categories'].apply(lambda x: x['title'] if isinstance(x, dict) else None)

# Merge con df_category_prices para traer el promedio de precio por categoría
df_exp = df_exp.merge(
    df_category_prices.rename(columns={'price_num': 'cat_avg_price'}),
    on='category_title',
    how='left'
)

# Imputar NaN de price_num con cat_avg_price
df_exp['price_num'] = df_exp['price_num'].fillna(df_exp['cat_avg_price'])

# Volver a reagrupar por restaurante
df_rest['price_num'] = df_exp.groupby(df_exp.index)['price_num'].mean()

#Convertir a Int64 para manejar nulos
df_rest['price_num'] = df_rest['price_num'].astype('Int64')

df_rest['price_num']

0      3
1      3
2      3
3      2
4      3
      ..
195    2
196    2
197    2
198    4
199    4
Name: price_num, Length: 200, dtype: Int64

In [15]:
#Ahora pasamos a analizar la columna review_count y rating
df_rest['review_count'].isna().sum()

np.int64(0)

In [16]:
(df_rest['review_count'] < 0).sum()

np.int64(0)

In [17]:
df_rest['rating'].unique()

array([4.5, 4.2, 4.7, 4.3, 4.6, 4.4, 4. , 4.1, 4.8, 3.8, 3.9, 5. , 3.6,
       3.4, 4.9, 1.2, 2.5, 3.5])

In [18]:
df_rest['review_count'].describe()

count     200.000000
mean      658.025000
std       875.701249
min         3.000000
25%       108.750000
50%       343.000000
75%       844.000000
max      6682.000000
Name: review_count, dtype: float64

In [19]:
#Guardamos el dataset en un csv
df_rest.to_csv("df_rest_boston.csv", index=False, encoding="utf-8")

CREACIÓN DE TABLAS Y ANALISIS DE LA INFORMACIÓN

1. Comenzamos por armar un Promedio Ponderado de los restaurantes para tener una medida mas precisa acorde a las reviews y el rating

In [20]:
# 1. Calcular promedio global de rating
C = df_rest['rating'].mean()

# 2. Definir mínimo de reviews para considerar (puede ser percentil 70)
m = df_rest['review_count'].quantile(0.80)

# 3. Función para calcular Weighted Rating
def weighted_rating(x, m=m, C=C):
    v = x['review_count']
    R = x['rating']
    return (v / (v + m)) * R + (m / (v + m)) * C

# 4. Crear nueva columna con Weighted Rating
df_rest['weighted_rating'] = df_rest.apply(weighted_rating, axis=1).round(2)

# 5. Ordenar de mayor a menor
df_rest_sorted = df_rest.sort_values('weighted_rating', ascending=False)

# Ver top 10 restaurantes
df_rest_sorted[['name', 'rating', 'review_count', 'weighted_rating']].head(10)

                             name  rating  review_count  weighted_rating
120           Ciao! Pizza & Pasta     4.8          1203             4.52
0                     Carmelina's     4.5          4126             4.44
11                   Cafe Bonjour     4.6          1064             4.40
114               Yume Ga Arukara     4.6           796             4.38
50   Mike & Patty's - Bay Village     4.4          2246             4.34
7                           Krasi     4.6           544             4.34
199             Fuji at Ink Block     4.5           765             4.33
14   Barcelona Wine Bar South End     4.4          1606             4.32
119                  Cafe Polonia     4.5           574             4.31
34                          Sarma     4.4          1355             4.31

Vinculamos al promedio ponderado con la categoria principal del restaurante

In [21]:
import ast

# --- 1. Procesar la columna categories ---
# Si la columna 'categories' está como string, convertirla a lista de diccionarios
df_rest['categories'] = df_rest['categories'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

# Crear nueva columna con títulos de categorías separados por coma
df_rest['categories_clean'] = df_rest['categories'].apply(lambda x: ', '.join([d['title'] for d in x]) if isinstance(x, list) else '')

# --- 2. Calcular promedio global de rating ---
C = df_rest['rating'].mean()

# --- 3. Definir mínimo de reviews (percentil 80 por ejemplo) ---
m = df_rest['review_count'].quantile(0.80)

# --- 4. Función Weighted Rating ---
def weighted_rating(x, m=m, C=C):
    v = x['review_count']
    R = x['rating']
    return (v / (v + m)) * R + (m / (v + m)) * C

# --- 5. Crear columna con Weighted Rating ---
df_rest['weighted_rating'] = df_rest.apply(weighted_rating, axis=1).round(2)

# --- 6. Ordenar ---
df_rest_sorted = df_rest.sort_values('weighted_rating', ascending=False)

# --- 7. Ver top 10 incluyendo categorías ---
df_rest_sorted[['name', 'categories_clean', 'rating', 'review_count', 'weighted_rating']].head(10)

,name,categories_clean,rating,review_count,weighted_rating
120,Ciao! Pizza & Pasta,"Italian, Pizza",4.8,1203,4.52
0,Carmelina's,Italian,4.5,4126,4.44
11,Cafe Bonjour,"Breakfast & Brunch, Coffee & Tea, Sandwiches",4.6,1064,4.40
114,Yume Ga Arukara,"Japanese, Noodles",4.6,796,4.38
50,Mike & Patty's - Bay Village,"Sandwiches, Breakfast & Brunch",4.4,2246,4.34
7,Krasi,"Mediterranean, Greek, Wine Bars",4.6,544,4.34
199,Fuji at Ink Block,"Japanese, Sushi Bars, Cocktail Bars",4.5,765,4.33
14,Barcelona Wine Bar South End,"Spanish, Wine Bars, Tapas/Small Plates",4.4,1606,4.32
119,Cafe Polonia,"Polish, Wine Bars, Modern European",4.5,574,4.31
34,Sarma,"Middle Eastern, Tapas/Small Plates, Mediterranean",4.4,1355,4.31

2. Usamos la columna transaccion como parametro para ver si hay patrones entre el promedio ponderado y los servicios que prestan los restaurantes (derivery, 
pickup, reservaciones)

In [22]:
# Convertir de string a lista si están guardados como texto
df_rest['transactions'] = df_rest['transactions'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

# Aplanar y obtener únicos
transactions_unicos = set([t for sublist in df_rest['transactions'].dropna() for t in sublist])
print(transactions_unicos)

{'delivery', 'restaurant_reservation', 'pickup'}

In [23]:
#Creamos columnas "dummy" para establecer estas relaciones, es decir, le asignamos un numero 1 de acuerdo con cada servicio prestado por el restaurante
df_rest['pickup_dummy'] = df_rest['transactions'].apply(lambda x: 1 if 'pickup' in x else 0)
df_rest['delivery_dummy'] = df_rest['transactions'].apply(lambda x: 1 if 'delivery' in x else 0)
df_rest['reservation_dummy'] = df_rest['transactions'].apply(lambda x: 1 if 'restaurant_reservation' in x else 0)

df_rest_sorted['pickup_dummy'] = df_rest['transactions'].apply(lambda x: 1 if 'pickup' in x else 0)
df_rest_sorted['delivery_dummy'] = df_rest['transactions'].apply(lambda x: 1 if 'delivery' in x else 0)
df_rest_sorted['reservation_dummy'] = df_rest['transactions'].apply(lambda x: 1 if 'restaurant_reservation' in x else 0)


df_rest_sorted[['name', 'categories_clean', 'weighted_rating', 
                'pickup_dummy', 'delivery_dummy', 'reservation_dummy','price_num']].head(10)

,name,categories_clean,weighted_rating,pickup_dummy,delivery_dummy,reservation_dummy,price_num
120,Ciao! Pizza & Pasta,"Italian, Pizza",4.52,0,1,0,2
0,Carmelina's,Italian,4.44,0,1,1,3
11,Cafe Bonjour,"Breakfast & Brunch, Coffee & Tea, Sandwiches",4.40,1,1,0,2
114,Yume Ga Arukara,"Japanese, Noodles",4.38,0,1,0,2
50,Mike & Patty's - Bay Village,"Sandwiches, Breakfast & Brunch",4.34,1,1,0,2
7,Krasi,"Mediterranean, Greek, Wine Bars",4.34,0,1,0,2
199,Fuji at Ink Block,"Japanese, Sushi Bars, Cocktail Bars",4.33,1,1,0,4
14,Barcelona Wine Bar South End,"Spanish, Wine Bars, Tapas/Small Plates",4.32,0,1,0,2
119,Cafe Polonia,"Polish, Wine Bars, Modern European",4.31,1,1,0,2
34,Sarma,"Middle Eastern, Tapas/Small Plates, Mediterranean",4.31,0,1,0,2